// <auto-generated />
namespace ContactsWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202102061416_DataBase_Model_UpdateAdd_Address_Other_Fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202102061416_DataBase_Model_UpdateAdd_Address_Other_Fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202102061716365_202102061416_DataBase_Model_Update-Add_Address_Other_Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
